### ISSUE TITLE
TODO: Set up a Virtual Machine for Hosting. 

### ISSUE THREAD

**Issue by MrExternal** [MrExternal/mf0DJnN#7]
*I actually have no idea how this works..* 

Reminder to set up a virtual machine (equipped w/ Windows 10) for hosting purposes on the server. 
Sooner it is done, the better.

**Comment by Grant11** [comment]
Uhhhhh you are gay

**Comment by Grant11** [comment]
You cant host on a "Virtual Machine" it has to be on a Virtual.Private.Server (VPS) and a VPS cost money. So unless some one has money it will have to be hosted on some ones modem

**Comment by NickdogeGaming** [comment]
Yes, setup a VirtualBox and install team viewer
